do nothing
[Modelarts Service Log]user: uid=1101(work) gid=1101(work) groups=1101(work)
[Modelarts Service Log]pwd: /home/work
[Modelarts Service Log]app_url: s3://resnext-tk/MA-ResNeXt-in-tensorflow-master-11-03-14-34/code/
[Modelarts Service Log]boot_file: code/cifar10_train.py
[Modelarts Service Log]log_url: /tmp/log/MA-ResNeXt-in-tensorflow-master-11-03-14-34.log
[Modelarts Service Log]command: code/cifar10_train.py --data_url=s3://resnext-tk/ResNeXt-in-tensorflow-master/cifar10_data/cifar-10-batches-py/ --train_url=s3://resnext-tk/MA-ResNeXt-in-tensorflow-master-11-03-14-34/output/V0014/ --num_gpus=1
[Modelarts Service Log]MODELARTS_IPOIB_DEVICE: 
[Modelarts Service Log]dependencies_file_dir: /home/work/user-job-dir/code
[Modelarts Service Log][modelarts_create_log] modelarts-pipe found
[Modelarts Service Log]handle inputs of training job
INFO:root:Using MoXing-v1.17.3-4c644d5b
INFO:root:Using OBS-Python-SDK-3.20.7
[ModelArts Service Log][INFO][2020/11/06 16:43:29]: env MA_INPUTS is not found, skip the inputs handler
INFO:root:Using MoXing-v1.17.3-4c644d5b
INFO:root:Using OBS-Python-SDK-3.20.7
[ModelArts Service Log]2020-11-06 16:43:30,068 - modelarts-downloader.py[line:619] - INFO: Main: modelarts-downloader starting with Namespace(dst='./', recursive=True, skip_creating_dir=False, src='s3://resnext-tk/MA-ResNeXt-in-tensorflow-master-11-03-14-34/code/', trace=False, type='common', verbose=False)
/home/work/user-job-dir
mkdir: cannot create directory ‘logs’: File exists
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-ResNeXt-in-tensorflow-master-11-03-14-34.log
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-ResNeXt-in-tensorflow-master-11-03-14-34.log
[ModelArts Service Log]modelarts-pipe: will write log file /tmp/log/MA-ResNeXt-in-tensorflow-master-11-03-14-34.log
[ModelArts Service Log]modelarts-pipe: param for max log length: 1073741824
[Modelarts Service Log][modelarts_logger] modelarts-pipe found
[ModelArts Service Log]modelarts-pipe: param for whether exit on overflow: 0
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.
Successfully downloaded cifar-10-python.tar.gz 170498071 bytes.
['cifar10_data/cifar-10-batches-py/data_batch_1', 'cifar10_data/cifar-10-batches-py/data_batch_2', 'cifar10_data/cifar-10-batches-py/data_batch_3', 'cifar10_data/cifar-10-batches-py/data_batch_4', 'cifar10_data/cifar-10-batches-py/data_batch_5']
Reading images from cifar10_data/cifar-10-batches-py/data_batch_1
Reading images from cifar10_data/cifar-10-batches-py/data_batch_2
Reading images from cifar10_data/cifar-10-batches-py/data_batch_3
Reading images from cifar10_data/cifar-10-batches-py/data_batch_4
Reading images from cifar10_data/cifar-10-batches-py/data_batch_5
Shuffling
['cifar10_data/cifar-10-batches-py/test_batch']
Reading images from cifar10_data/cifar-10-batches-py/test_batch
Shuffling
WARNING:tensorflow:From /home/work/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /cache/user-job-dir/code/resNeXt.py:56: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
WARNING:tensorflow:From code/cifar10_train.py:276: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/work/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From code/cifar10_train.py:86: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
WARNING:tensorflow:From /home/work/anaconda/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2020-11-06 16:43:54.000013: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-11-06 16:43:54.196013: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55752acdc4e0 executing computations on platform CUDA. Devices:
2020-11-06 16:43:54.196052: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla V100-PCIE-32GB, Compute Capability 7.0
2020-11-06 16:43:54.223292: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000000000 Hz
2020-11-06 16:43:54.223803: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55752adf7f20 executing computations on platform Host. Devices:
2020-11-06 16:43:54.223831: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-11-06 16:43:54.223965: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:21:01.0
totalMemory: 31.75GiB freeMemory: 31.44GiB
2020-11-06 16:43:54.223985: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-11-06 16:43:54.226338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-06 16:43:54.226372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-11-06 16:43:54.226379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-11-06 16:43:54.226458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30583 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:21:01.0, compute capability: 7.0)
2020-11-06 16:43:57.092931: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing config loader against fileName /home/work//.aws/config and using profilePrefix = 1
2020-11-06 16:43:57.092976: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing config loader against fileName /run/secrets/kubernetes.io/batch/config and using profilePrefix = 0
2020-11-06 16:43:57.092987: I tensorflow/core/platform/s3/aws_logging.cc:54] Setting provider to read credentials from /run/secrets/kubernetes.io/batch/config for credentials file and /home/work//.aws/config for the config file , for use with profile default
2020-11-06 16:43:57.093000: I tensorflow/core/platform/s3/aws_logging.cc:54] Creating HttpClient with max connections2 and scheme http
2020-11-06 16:43:57.093444: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing CurlHandleContainer with size 2
2020-11-06 16:43:57.093472: I tensorflow/core/platform/s3/aws_logging.cc:54] Creating Instance with default EC2MetadataClient and refresh rate 900000
2020-11-06 16:43:57.093596: I tensorflow/core/platform/s3/aws_logging.cc:54] Successfully reloaded configuration.
2020-11-06 16:43:57.094712: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing CurlHandleContainer with size 25
2020-11-06 16:43:57.096262: I tensorflow/core/platform/s3/aws_logging.cc:54] Pool grown by 2
2020-11-06 16:43:57.096282: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:43:57.269114: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:43:57.291878: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:43:57.300054: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:43:57.858395: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:43:57.871844: W tensorflow/core/platform/s3/aws_logging.cc:57] Encountered Unknown AWSError
InvalidSecuToken
security token is invalid:
2020-11-06 16:43:57.871887: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2020-11-06 16:43:57.871924: E tensorflow/core/util/events_writer.cc:108] Write failed because file could not be opened.
2020-11-06 16:43:57.872204: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:43:57.909067: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:43:57.922624: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
Start training...
----------------------------
2020-11-06 16:43:59.209255: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2020-11-06 16:44:03.831019: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:04.173982: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:04.191771: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:09.431872: step 0, loss = 4.0994 (42.2 examples/sec; 3.036 sec/batch)
Train top1 error =  0.8984375
Validation top1 error = 0.9039
Validation loss =  2.8804653
----------------------------
2020-11-06 16:44:09.665370: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:09.691686: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20201106T0844091604652249665
2020-11-06 16:44:09.702266: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:09.920301: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20201106T0844091604652249691
2020-11-06 16:44:09.922668: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:09.934810: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.296637: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.310753: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.327140: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20201106T0844101604652250310
2020-11-06 16:44:10.327329: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.342491: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.365274: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.380528: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.396258: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20201106T0844101604652250380
2020-11-06 16:44:10.396504: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.409431: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.428024: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.736667: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.746836: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404
2020-11-06 16:44:10.746874: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2020-11-06 16:44:10.747002: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:10.907439: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:11.171680: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20201106T0844101604652250904
2020-11-06 16:44:11.172965: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:11.192574: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2020-11-06 16:44:11.253808: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
Traceback (most recent call last):
  File "/home/work/anaconda/lib/python3.6/site-packages/pandas/io/s3.py", line 5, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "code/cifar10_train.py", line 404, in <module>
    train.train()
  File "code/cifar10_train.py", line 194, in train
    df.to_csv(train_dir + FLAGS.version + '_error.csv')
  File "/home/work/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 3019, in to_csv
    escapechar=escapechar, decimal=decimal)
  File "/home/work/anaconda/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 44, in __init__
    path_or_buf, encoding=encoding, compression=compression, mode=mode
  File "/home/work/anaconda/lib/python3.6/site-packages/pandas/io/common.py", line 212, in get_filepath_or_buffer
    from pandas.io import s3
  File "/home/work/anaconda/lib/python3.6/site-packages/pandas/io/s3.py", line 8, in <module>
    raise ImportError("The s3fs library is required to handle s3 files")
ImportError: The s3fs library is required to handle s3 files
[ModelArts Service Log]modelarts-pipe: total length: 12529
[Modelarts Service Log]Training end with return code: 1
[Modelarts Service Log]Training completed.
